# Generated by Django 3.1.7 on 2021-05-15 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_auto_20210507_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('location_desc', models.CharField(blank=True, max_length=300)),
                ('location_log', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=50)),
                ('venue_type', models.CharField(blank=True, choices=[('', ''), ('Marriage Hall', 'Marriage Hall'), ('Conference Hall', 'Conference Hall'), ('Auditorium', 'Auditorium'), ('Party/Celebration Hall', 'Party/Celebration Hall')], max_length=30)),
                ('venue_phone', models.CharField(max_length=30)),
                ('venue_office', models.CharField(blank=True, max_length=30)),
                ('venue_rate', models.CharField(max_length=30)),
                ('venue_desc', models.CharField(blank=True, max_length=300)),
                ('venue_log', models.DateTimeField(auto_now_add=True)),
                ('venue_picture', models.ImageField(blank=True, upload_to='venue')),
                ('venue_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.location')),
            ],
        ),
    ]
