# Generated by Django 3.1.7 on 2021-05-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_location_venuemanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringservice',
            name='cat_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.location'),
        ),
        migrations.AlterField(
            model_name='makeupartist',
            name='mua_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.location'),
        ),
    ]
