# Generated by Django 3.1.7 on 2021-05-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_auto_20210515_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('status_desc', models.CharField(blank=True, max_length=300)),
                ('status_log', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='makeupartist',
            name='mua_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseApp.location'),
        ),
        migrations.AlterField(
            model_name='makeupartist',
            name='specification',
            field=models.CharField(blank=True, choices=[('', ''), ('MAC', 'MAC'), ('Normal', 'Normal')], max_length=30),
        ),
    ]
