# Generated by Django 3.1.7 on 2021-05-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_auto_20210515_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicefor', models.CharField(max_length=30)),
                ('servicefor_desc', models.CharField(blank=True, max_length=300)),
                ('servicefor_log', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='makeupartist',
            name='mua_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.location'),
        ),
        migrations.AddField(
            model_name='cateringservice',
            name='servicefor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='baseApp.servicefor'),
        ),
        migrations.AddField(
            model_name='makeupartist',
            name='servicefor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseApp.servicefor'),
        ),
        migrations.AddField(
            model_name='venuemanagement',
            name='servicefor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='baseApp.servicefor'),
        ),
    ]
