# Generated by Django 3.1.7 on 2021-05-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_auto_20210515_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringservice',
            name='servicefor',
        ),
        migrations.RemoveField(
            model_name='makeupartist',
            name='servicefor',
        ),
        migrations.RemoveField(
            model_name='venuemanagement',
            name='servicefor',
        ),
    ]
