# Generated by Django 3.1.7 on 2021-05-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_auto_20210515_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceFor',
        ),
    ]
