# Generated by Django 3.1.7 on 2021-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_makeupartist_servicefor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringservice',
            name='servicefor',
            field=models.CharField(blank=True, choices=[('MAKEUP ARTIST', 'MAKEUP ARTIST'), ('CATERING SERVICES', 'CATERING SERVICES'), ('VENUE', 'VENUE')], default='CATERING SERVICES', max_length=30),
        ),
        migrations.AddField(
            model_name='venuemanagement',
            name='servicefor',
            field=models.CharField(blank=True, choices=[('MAKEUP ARTIST', 'MAKEUP ARTIST'), ('CATERING SERVICES', 'CATERING SERVICES'), ('VENUE', 'VENUE')], default='VENUE', max_length=30),
        ),
    ]
