# Generated by Django 3.1.7 on 2021-05-15 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0012_auto_20210515_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(max_length=50)),
                ('reguest_for', models.CharField(max_length=50)),
                ('request_user', models.CharField(max_length=50)),
                ('request_user_phone', models.CharField(max_length=50)),
                ('request_booking_date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('booking_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseApp.bookingstatus')),
            ],
        ),
    ]
