# Generated by Django 3.1.7 on 2021-05-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0013_bookingmanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingManagement',
        ),
    ]
