# Generated by Django 3.1.7 on 2021-05-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0017_auto_20210516_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmanagement',
            name='status_change_message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
