# Generated by Django 3.1.6 on 2021-05-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0019_packagemanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageManagement',
        ),
    ]
