# Generated by Django 3.1.6 on 2021-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0020_delete_packagemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, choices=[('', ''), ('Marriage', 'Marriage'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=30)),
                ('event_caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.cateringservice')),
                ('event_mua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.makeupartist')),
                ('event_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.venuemanagement')),
            ],
        ),
    ]
