# Generated by Django 3.1.6 on 2021-05-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0021_packagemanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemanagement',
            name='event_mua',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='baseApp.makeupartist'),
        ),
    ]
