# Generated by Django 3.1.7 on 2021-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0022_annispecial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annispecial',
            name='picture',
            field=models.ImageField(blank=True, upload_to='Anni'),
        ),
    ]
