# Generated by Django 3.1.6 on 2021-05-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0022_auto_20210517_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_name', models.CharField(max_length=30)),
                ('dec_style', models.CharField(choices=[('', ''), ('Marriage', 'Marriage'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=30)),
                ('dec_location', models.CharField(max_length=50)),
                ('dec_range', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='packagemanagement',
            name='event_caterer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.cateringservice'),
        ),
        migrations.AlterField(
            model_name='packagemanagement',
            name='event_type',
            field=models.CharField(choices=[('', ''), ('Marriage', 'Marriage'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=30),
        ),
        migrations.AlterField(
            model_name='packagemanagement',
            name='event_venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.venuemanagement'),
        ),
    ]
