# Generated by Django 3.1.6 on 2021-05-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0023_auto_20210521_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decorators',
            new_name='Decorator',
        ),
    ]
