# Generated by Django 3.1.7 on 2021-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0024_annitheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annitheme',
            name='theme_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
