# Generated by Django 3.1.6 on 2021-05-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0025_decorator_dec_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGrapher',
            fields=[
                ('pht_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pht_adress', models.CharField(max_length=30)),
                ('pht_profile', models.CharField(max_length=80)),
                ('pht_range', models.CharField(max_length=30)),
                ('pht_sample1', models.ImageField(blank=True, upload_to='Photographer')),
                ('pht_sample2', models.ImageField(blank=True, upload_to='Photographer')),
                ('pht_sample3', models.ImageField(blank=True, upload_to='Photographer')),
            ],
        ),
        migrations.RemoveField(
            model_name='decorator',
            name='id',
        ),
        migrations.AlterField(
            model_name='decorator',
            name='dec_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
