# Generated by Django 3.1.7 on 2021-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0025_auto_20210517_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnniPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1st Anniversary Celebration', '1'), ('2nd Anniversary Celebration', '2'), ('3rd Anniversary Celebration', '3'), ('5th Anniversary Celebration', '5'), ('Silver Anniversary Celebration', '25'), ('Golden Anniversary Celebration', '50')], max_length=100)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('picture', models.ImageField(blank=True, upload_to='Anni')),
            ],
        ),
    ]
