# Generated by Django 3.1.6 on 2021-05-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0026_auto_20210523_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemanagement',
            name='event_thumbnail',
            field=models.ImageField(blank=True, upload_to='package'),
        ),
    ]
