# Generated by Django 3.1.7 on 2021-05-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0028_auto_20210519_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('type_desc', models.CharField(blank=True, max_length=300)),
                ('vtype_log', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='venuemanagement',
            name='venue_picture',
            field=models.ImageField(blank=True, upload_to='VENUEs'),
        ),
        migrations.AlterField(
            model_name='venuemanagement',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Marriage Hall', 'Marriage Hall'), ('Conference Hall', 'Conference Hall'), ('Auditorium', 'Auditorium'), ('Party Hall', 'Party Hall')], max_length=30),
        ),
    ]
