# Generated by Django 3.1.6 on 2021-05-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0029_auto_20210530_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemanagement',
            name='event_decor',
        ),
    ]
