# Generated by Django 3.1.7 on 2021-05-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0029_auto_20210520_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenuebType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('type_desc', models.CharField(blank=True, max_length=300)),
                ('vtype_log', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='venuemanagement',
            name='venue_picture',
            field=models.ImageField(blank=True, upload_to='venues'),
        ),
        migrations.AlterField(
            model_name='venuemanagement',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Marriage Hall', 'Marriage Hall'), ('Conference Hall', 'Conference Hall'), ('Auditorium', 'Auditorium'), ('Party Hall', 'Party Hall'), ('Birthday Hall', 'Birthday Hall')], max_length=30),
        ),
        migrations.CreateModel(
            name='VenuebbManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueb_name', models.CharField(max_length=50)),
                ('venueb_type', models.CharField(blank=True, choices=[('', ''), ('Party Hall', 'Party Hall'), ('Birthday Kid Hall', 'Birthday Kid Hall')], max_length=30)),
                ('venueb_phone', models.CharField(max_length=30)),
                ('venueb_office', models.CharField(blank=True, max_length=30)),
                ('venueb_rate', models.CharField(max_length=30)),
                ('venueb_desc', models.CharField(blank=True, max_length=300)),
                ('venueb_log', models.DateTimeField(auto_now_add=True)),
                ('venueb_picture', models.ImageField(blank=True, upload_to='venuebs')),
                ('servicefor', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='baseApp.servicefor')),
                ('venueb_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.location')),
            ],
        ),
    ]
