# Generated by Django 3.1.6 on 2021-05-30 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0030_remove_packagemanagement_event_decor'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemanagement',
            name='event_decor',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='baseApp.decorator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagemanagement',
            name='event_mua',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.makeupartist'),
        ),
    ]
