# Generated by Django 3.1.7 on 2021-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0030_auto_20210525_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuemanagement',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Marriage Hall', 'Marriage Hall'), ('Conference Hall', 'Conference Hall'), ('Auditorium', 'Auditorium'), ('Party Hall', 'Party Hall'), ('Party Ground', 'Party Ground'), ('Birthday Hall', 'Birthday Hall')], max_length=30),
        ),
    ]
