# Generated by Django 3.1.7 on 2021-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0031_auto_20210529_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1st Anniversary Celebration', '1'), ('2nd Anniversary Celebration', '2'), ('3rd Anniversary Celebration', '3'), ('4th Anniversary Celebration', '4'), ('5th Anniversary Celebration', '5'), ('6th Anniversary Celebration', '6'), ('7th Anniversary Celebration', '7'), ('8th Anniversary Celebration', '8'), ('9th Anniversary Celebration', '9'), ('10th Anniversary Celebration', '10'), ('11th Anniversary Celebration', '11'), ('12th Anniversary Celebration', '12'), ('13th Anniversary Celebration', '13'), ('14th Anniversary Celebration', '14'), ('15th Anniversary Celebration', '15'), ('16th Anniversary Celebration', '16'), ('17th Anniversary Celebration', '17'), ('18th Anniversary Celebration', '18'), ('19th Anniversary Celebration', '19'), ('20th Anniversary Celebration', '20'), ('Silver Anniversary Celebration', '25'), ('Golden Anniversary Celebration', '50')], max_length=100)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('picture', models.ImageField(blank=True, upload_to='Birthday')),
            ],
        ),
    ]
