# Generated by Django 3.1.6 on 2021-05-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0031_auto_20210530_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemanagement',
            name='event_caterer',
        ),
        migrations.RemoveField(
            model_name='packagemanagement',
            name='event_decor',
        ),
        migrations.RemoveField(
            model_name='packagemanagement',
            name='event_mua',
        ),
        migrations.RemoveField(
            model_name='packagemanagement',
            name='event_thumbnail',
        ),
        migrations.RemoveField(
            model_name='packagemanagement',
            name='event_venue',
        ),
    ]
