# Generated by Django 3.1.6 on 2021-05-30 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0032_auto_20210530_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemanagement',
            name='event_venue',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='baseApp.venuemanagement'),
            preserve_default=False,
        ),
    ]
