# Generated by Django 3.1.7 on 2021-05-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0032_birthdaypics'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('picture', models.ImageField(blank=True, upload_to='Wedding')),
            ],
        ),
        migrations.AlterField(
            model_name='birthdaypics',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
