# Generated by Django 3.1.6 on 2021-05-30 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0033_packagemanagement_event_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagesManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('', ''), ('Marriage', 'Marriage'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=30)),
                ('event_thumbnail', models.ImageField(upload_to='package')),
                ('event_caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.cateringservice')),
                ('event_decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.decorator')),
                ('event_mua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.makeupartist')),
                ('event_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.venuemanagement')),
            ],
        ),
    ]
