# Generated by Django 3.1.6 on 2021-05-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0034_packagesmanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageManagement',
        ),
    ]
