# Generated by Django 3.1.6 on 2021-05-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0035_delete_packagemanagement'),
        ('baseApp', '0033_auto_20210529_0307'),
    ]

    operations = [
    ]
