# Generated by Django 3.1.6 on 2021-05-31 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0036_merge_20210530_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('', ''), ('Marriage', 'Marriage'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=30)),
                ('event_thumbnail', models.ImageField(blank=True, upload_to='package')),
                ('event_rate', models.CharField(max_length=10)),
                ('event_caterer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.cateringservice')),
                ('event_decor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.decorator')),
                ('event_mua', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.makeupartist')),
                ('event_venue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.venuemanagement')),
            ],
        ),
        migrations.DeleteModel(
            name='PackagesManagement',
        ),
    ]
