# Generated by Django 3.1.6 on 2021-06-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0037_auto_20210531_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemanagement',
            name='event_rate',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
