# Generated by Django 3.1.6 on 2021-06-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0038_auto_20210613_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('feedbacks', models.TextField()),
            ],
        ),
    ]
