# Generated by Django 3.1.6 on 2021-07-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0040_auto_20210702_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmanagement',
            name='request_user_phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
