# Generated by Django 3.1.6 on 2021-07-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0041_auto_20210702_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmanagement',
            name='request_user_phone',
            field=models.CharField(max_length=10),
        ),
    ]
